apiVersion: apps/v1
kind: Deployment
metadata:
  name: embeddedserverapp-deployment
  namespace: embeddedserverapp
  annotations:
    redeploy-timestamp: "2026-02-12-21-20"   # forces new ReplicaSet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: embeddedserverapp
  template:
    metadata:
      labels:
        app: embeddedserverapp
    spec:
      containers:
      - name: embeddedserverapp
        image: srinivasacr.azurecr.io/embeddedserverapp@sha256:29a843c5c138d5838eb374be2a5ec1e3a42aa99f7db524c1a153800716a68d77
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        imagePullPolicy: Always
      restartPolicy: Always