apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: embeddedserverapp-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - host: 123.45.67.89.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: embeddedserverapp-service
            port:
              number: 80
