apiVersion: v1
kind: Service
metadata:
  name: embeddedserverapp-service
  namespace: embeddedserverapp
spec:
  type: LoadBalancer
  selector:
    app: embeddedserverapp
  ports:
    - port: 80
      targetPort: 8080