apiVersion: v1
kind: Service
metadata:
  name: embeddedserverapp-service
spec:
  type: LoadBalancer
  selector:
    app: embeddedserverapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
