apiVersion: v1
kind: Service
metadata:
  name: webapp-service-new
  namespace: webapp
spec:
  type: LoadBalancer
  loadBalancerIP: 20.9.90.119
  selector:
    app: webapp
  ports:
    - port: 80
      targetPort: 8080